DROP SCHEMA IF EXISTS pseudo_stone;
CREATE SCHEMA pseudo_stone DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE pseudo_stone;

CREATE TABLE transaction(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  metaId VARCHAR(255) NULL DEFAULT NULL,
  amount INT UNSIGNED NULL DEFAULT NULL,
  authorized TINYINT UNSIGNED NULL DEFAULT NULL,
  authorisationResponse VARCHAR(255) NULL DEFAULT NULL,
  authorisationResponseReason VARCHAR(255) NULL DEFAULT NULL,
  captured TINYINT UNSIGNED NULL DEFAULT NULL,
  cancelled TINYINT UNSIGNED NULL DEFAULT NULL,
  cancelledAt DATETIME NULL DEFAULT NULL,
  capturedAt DATETIME NULL DEFAULT NULL,
  createdAt DATETIME NULL DEFAULT NULL,

  PRIMARY KEY (id)
)ENGINE = InnoDB;